name: formatting

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Deno
        id: setup-deno
        uses: denoland/setup-deno@v1.1.3
        with:
          deno-version: v1.38.3

      - run: deno fmt --check
